steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
      '-t', 'gcr.io/$PROJECT_ID/word-lapse-api-image:${_COMMIT_SHA}',
      '--cache-from', 'gcr.io/$PROJECT_ID/word-lapse-api-image:latest',
      '--build-arg', 'SHORT_SHA=${_SHORT_SHA}',
      '--build-arg', 'COMMIT_SHA=${_COMMIT_SHA}',
      '.'
  ]
images:
- 'gcr.io/$PROJECT_ID/word-lapse-api-image:${_COMMIT_SHA}'
timeout: '7200s'